package com.rx.dao;


public enum DocumentType {
    SYLLABUS,
    NORMATIVE_ACT,
    TEACHING_LOAD,

    TRAINING_PROGRAM,
    WORK_PROGRAM,
    THEORETICAL_PART_TEXTBOOKS,
    THEORETICAL_PART_TUTORIALS,
    THEORETICAL_PART_LECTURE_NOTES,
    PRACTICAL_LESSON_TUTORIALS,
    PRACTICAL_LESSON_GUIDELINES,
    LABORATORY_WORK_TUTORIALS,
    LABORATORY_WORK_GUIDELINES,
    COURSE_WORK_TUTORIALS,
    COURSE_WORK_GUIDELINES,
    DIPLOMA_WORK_TUTORIALS,
    DIPLOMA_WORK_GUIDELINES,
    COMPLEX_TEST_METHODOLOGICAL_MATERIALS,
    PROGRAM_MODULES_ADOPTION_LEVEL_DIAGNOSIS_METHODOLOGICAL_MATERIALS,
    INTELLIGENT_COMPUTER_SIMULATORS,
    VIRTUAL_LABORATORY_AND_PRACTICAL_WORK,
    EXTRAMULAR_STUDIES_MULTIMEDIA_LECTURES,
    EXTRAMULAR_STUDIES_INDEPENDENT_WORK_TUTORIALS,
    EXTRAMULAR_STUDIES_INDEPENDENT_WORK_GUIDELINES,
    PRACTICE_TUTORIALS,
    PRACTICE_GUIDELINES
}
